NorthwindMVC.Website/Models/CategoryViewModel.cs
using NorthwindDAL.Entities;
using NorthwindMVC.Website.Models.Base;
using System.Collections.Generic;

namespace NorthwindMVC.Website.Models
{
    public class CategoryViewModel : ICanShowAsCard
    {
        public CategoryViewModel(Category category, string webRootPath = "")
        {
            Id = category.CategoryID;
            Title = category.CategoryName;
            Text = category.Description;
            Image = $"category{Id}.jpeg";
            if (category.Products != null && !string.IsNullOrEmpty(webRootPath))
            {
                BriefProducts = new List<ICanShowAsCard>();
                foreach (var product in category.Products)
                {
                    BriefProducts.Add(new ProductViewModel(product, webRootPath));
                }
            }
        }

        public int Id { get; }

        public string Title { get; }

        public string Text { get; }

        public string Image { get; }

        public IList<ICanShowAsCard> BriefProducts { get; set; }

        public string Controller => "Categories";

        public string Action => "Details";
    }
}

NorthwindMVC.Website/Controllers/CategoriesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NorthwindDAL.Entities;
using NorthwindMVC.DAL;
using NorthwindMVC.Website.Models;

namespace NorthwindMVC.Website.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly NorthwindDB _context;
        private readonly IWebHostEnvironment _env;
        public CategoriesController(NorthwindDB context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = await _context.Categories
                .Include(category => category.Products)
                .FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(new CategoryViewModel(category, _env.WebRootPath));
        }

        // GET: Categories/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("CategoryID,CategoryName,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryID,CategoryName,Description")] Category category)
        {
            if (id != category.CategoryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryID == id);
        }
    }
}

NorthwindMVC.Website/ViewComponents/MyGenericCarouselViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NorthwindMVC.Website.Models;

namespace NorthwindMVC.Website.ViewComponents
{
    public class MyGenericCarouselViewComponent : ViewComponent
    {
        public MyGenericCarouselViewComponent()
        {
        }

        public IViewComponentResult Invoke(CarouselViewModel toDisplay)
        {
            return View(toDisplay);
        }
    }
}

NorthwindMVC.Website/Views/Categories/Create.cshtml
@model NorthwindDAL.Entities.Category

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NorthwindMVC.Website/Views/Categories/Delete.cshtml
@model NorthwindDAL.Entities.Category

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoryID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NorthwindMVC.Website/Views/Categories/Details.cshtml
@model CategoryViewModel

@{
    ViewData["Title"] = $"{@Model.Title} Details";
}

<h1>@Html.DisplayFor(model => model.Title)</h1>
<h2>@Html.DisplayFor(model => model.Text)</h2>

<div>
    @await Component.InvokeAsync("MyGenericCarousel", new CarouselViewModel("BriefProducts", @Model.BriefProducts, 4))
</div>

<div>
    @if (ViewContext.HttpContext.User.IsInRole("Administrator"))
    {
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    }
    <a asp-action="Index">Back to List</a>
</div>

NorthwindMVC.Website/Views/Categories/Edit.cshtml
@model NorthwindDAL.Entities.Category

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryID" />
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NorthwindMVC.Website/Views/Categories/Index.cshtml
@model List<NorthwindDAL.Entities.Category>

@{
    ViewData["Title"] = "Index";
}

<h1>Browse by Category:</h1>

@if (ViewContext.HttpContext.User.IsInRole("Administrator"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

@for (int c = 0; c < Model.Count; )
{
    <div class="card-deck mb-3 text-center">
        @for (int i = 0; i < 3 && c < Model.Count; i++, c++)
        {
            <div class="card mb-4 box-shadow">
                <a asp-action="Details" asp-route-id="@Model[c].CategoryID">
                    <img class="card-img-top" src="~/images/category@(Model[c].CategoryID).jpeg" alt="Card image">
                </a>
                <div class="card-body">
                    <h4 class="card-title"> @Html.DisplayFor(modelItem => Model[c].CategoryName)</h4>
                    <p class="card-text">@Html.DisplayFor(item => Model[c].Description)</p>
                    @if (ViewContext.HttpContext.User.IsInRole("Administrator"))
                    {
                        <a class="btn btn-info" style="margin-top: auto;" asp-action="Details" asp-route-id="@Model[c].CategoryID">Details</a>
                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model[c].CategoryID">Edit</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model[c].CategoryID">Delete</a>
                    }
                    else
                    {
                        <a class="btn btn-lg btn-block btn-info" style="margin-top: auto;" asp-action="Details" asp-route-id="@Model[c].CategoryID">Details</a>
                    }
                </div>
            </div>
        }
    </div>
}